// This file is generated by FBC.

#include "PUBLISH@postfix@.h"
#include <string.h>


#include <assert.h>

#ifdef _MSC_VER
#include <Winsock2.h>
#include <Ws2tcpip.h>
#else
#include <stdio.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#endif

/* PUBLISH@postfix@ initialization function */
void PUBLISH@postfix@init(PUBLISH@postfix@* me)
{
    memset(me, 0, sizeof(PUBLISH@postfix@));
}

void PUBLISH@postfix@sendPublisher(PUBLISH@postfix@* me)
{
	Publisher* pub = &me->publish;
	size_t size = 0;
	
	if (pub->sockfd <= 0) {
		printf("PUBLISHER - Error: Cannot write to uninitialized socket\n");
		return;
	}
	
	@begin_varlist#SD_@
	assert((size + sizeof(me->_@var@)) <= UDPBUFSIZE);
	memmove(pub->buffer + size, &me->_@var@, sizeof(me->_@var@));
	size += sizeof(me->_@var@);
	
	@end_varlist@
	
	if ( sendto(pub->sockfd, pub->buffer, size, 0, (struct sockaddr*)&(pub->dstAddr), 
	            sizeof(pub->dstAddr)) < 0 ) {
		perror("PUBLISHER - Error sending data through socket");
#ifdef _MSC_VER
		printf("PUBLISHER - WSAGetLastError: %d\n", WSAGetLastError());
#endif
	}
}

/* PUBLISH@postfix@ execution function */
void PUBLISH@postfix@run(PUBLISH@postfix@* me)
{
	me->_output.events = 0;

	if (me->_input.event.INIT) {
		me->QI = me->_QI;
		strncpy(me->ID, me->_ID, MAX_ID_LEN);
	}
	if (me->_input.event.REQ) {
		me->QI = me->_QI;
	}
	
	if (!me->_entered) {
		me->_entered = true;
	}
	else {									
		if (me->_input.event.INIT) {
			if (me->QI) {
				openPublisher(&me->publish, 1, me->ID);
				me->QO = true;
				strncpy(me->STATUS, "OK", MAX_STATUS_LEN);
				me->_output.event.INITO = 1;
			}
			else {
				closePublisher(&me->publish);
				me->QO = false;
				strncpy(me->STATUS, "", MAX_STATUS_LEN);
				me->_output.event.INITO = 1;
			}
		}
		else if (me->_input.event.REQ) {
			if (me->QI) {
				PUBLISH@postfix@sendPublisher(me);
				me->QO = true;
				strncpy(me->STATUS, "OK", MAX_STATUS_LEN);
				me->_output.event.CNF = 1;
			}
			else {
				me->QO = false;
				strncpy(me->STATUS, "INHIBITED", MAX_STATUS_LEN);
				me->_output.event.CNF = 1;
			}
		}
	}	
	me->_input.events = 0;
	
	if (me->_output.event.INITO || me->_output.event.CNF) {
		me->_QO = me->QO;
		strncpy(me->_STATUS, me->STATUS, MAX_STATUS_LEN);
	}
}
