// This file is generated by FBC

#ifndef PUBLISH@postfix@_H_
#define PUBLISH@postfix@_H_

@copyFile#pubsub.h
@copyFile#pubsub.c
@copyFile#publisher.c
#include "pubsub.h"
#include "fbtypes.h"
@includeUserTypes@

typedef union {
	UDINT events;
	struct {
		UDINT INIT : 1; // service initialization
		UDINT REQ : 1; // service request
	} event;
} PUBLISH@postfix@IEvents;

typedef union {
	UDINT events;
	struct {
		UDINT INITO : 1; // initialization confirm
		UDINT CNF : 1; // service confirmation
	} event;
} PUBLISH@postfix@OEvents;

#define MAX_ID_LEN 31
#define MAX_STATUS_LEN 31
typedef struct {
	UINT _state;
	BOOL _entered;

	PUBLISH@postfix@IEvents _input;
	BOOL QI;
	BOOL _QI;
	char ID[MAX_ID_LEN + 1];
	char _ID[MAX_ID_LEN + 1];
	
	@begin_varlist#SD_@
	@type#C@ _@var@;
	@end_varlist@
	
	PUBLISH@postfix@OEvents _output;
	BOOL QO;
	BOOL _QO;
	char STATUS[MAX_STATUS_LEN + 1];
	char _STATUS[MAX_STATUS_LEN + 1];

	Publisher publish;
} PUBLISH@postfix@;

/* PUBLISH@postfix@ initialization function */
void PUBLISH@postfix@init(PUBLISH@postfix@* me);

/* PUBLISH@postfix@ execution function */
void PUBLISH@postfix@run(PUBLISH@postfix@* me);
void PUBLISH@postfix@sendPublisher(PUBLISH@postfix@* me);

#endif /*PUBLISH@postfix@_H_*/
