// This file is generated by FBC.

#ifndef PUBLISH_ED_INT@postfix@_H_
#define PUBLISH_ED_INT@postfix@_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT INIT : 1; // INIT
		UDINT REQ : 1; // REQ
    } event;
} PUBLISH_ED_INT@postfix@IEvents;

typedef union {
    UDINT events;
    struct {
        UDINT INITO : 1;
		UDINT CNF : 1;
    } event;
} PUBLISH_ED_INT@postfix@OEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    PUBLISH_ED_INT@postfix@IEvents _input;
    PUBLISH_ED_INT@postfix@OEvents _output;
	
	// Inputs
	BOOL _QI;
	char _ID[32];
	INT _BagCount;
	INT _BagIDData[20];
	INT _BagLPosData[20];
	INT _BagLengthData[20];
	
	// Outputs
	BOOL _QO;
	char _STATUS[32];
	
} PUBLISH_ED_INT@postfix@;

/* PUBLISH_ED_INT initialization function */
void PUBLISH_ED_INT@postfix@init(PUBLISH_ED_INT@postfix@* me);

/* PUBLISH_ED_INT execution function */
void PUBLISH_ED_INT@postfix@run(PUBLISH_ED_INT@postfix@* me);

#endif	// PUBLISH_ED_INT_H_
