// This file is generated by FBC.
#include "PUBLISH_ED_INT@postfix@.h"
#include <string.h>
#include <stdio.h>

// TODO: Rename

extern int PUBLISH_ED_INT@postfix@packdata(PUBLISH_ED_INT@postfix@* me);

/* PUBLISH_ED_INT@postfix@ initialization function */
void PUBLISH_ED_INT@postfix@init(PUBLISH_ED_INT@postfix@* me)
{
    memset(me, 0, sizeof(PUBLISH_ED_INT@postfix@));
}

/* PUBLISH_ED_INT@postfix@ execution function */
void PUBLISH_ED_INT@postfix@run(PUBLISH_ED_INT@postfix@* me)
{
	me->_output.events = 0;
	
	if (me->_input.event.INIT) {
		me->_output.event.INITO = 1;
	}
	if(me->_input.event.REQ)
	{
		me->_output.event.CNF = 1;
	}

	me->_input.events = 0;
}
