// This file is generated by FBC.

#include "WagoInputBlock.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void WagoInputBlockinit(WagoInputBlock* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.events = 0;
    me->_output.events = 0;
    me->DI0 = false;
    me->_DI0 = false;
    me->DI1 = false;
    me->_DI1 = false;
    me->DI2 = false;
    me->_DI2 = false;
    me->DI3 = false;
    me->_DI3 = false;
    me->DI4 = false;
    me->_DI4 = false;
    me->DI5 = false;
    me->_DI5 = false;
    me->DI6 = false;
    me->_DI6 = false;
    me->DI7 = false;
    me->_DI7 = false;
}

/* ECC algorithms */
// Normally executed algorithm
void WagoInputBlock_GetKBusInputs(WagoInputBlock* me)
{
// read byte from pab and show it on console
KbusOpen();
// read input value
KbusUpdate();

me->DI0 = (0x1 & pstPabIN->uc.Pab[me->ByteIndex]) > 0;
me->DI1 = (0x2 & pstPabIN->uc.Pab[me->ByteIndex]) > 0;
me->DI2 = (0x4 & pstPabIN->uc.Pab[me->ByteIndex]) > 0;
me->DI3 = (0x8 & pstPabIN->uc.Pab[me->ByteIndex]) > 0;
me->DI4 = (0x10 & pstPabIN->uc.Pab[me->ByteIndex]) > 0;
me->DI5 = (0x20 & pstPabIN->uc.Pab[me->ByteIndex]) > 0;
me->DI6 = (0x40 & pstPabIN->uc.Pab[me->ByteIndex]) > 0;
me->DI7 = (0x80 & pstPabIN->uc.Pab[me->ByteIndex]) > 0;

// Close
KbusClose();

}

/* Function block execution function */
void WagoInputBlockrun(WagoInputBlock* me)
{
    me->_output.events = 0;

    if (me->_input.events) {
        if (me->_input.event.INIT) {
            me->ByteIndex = me->_ByteIndex;
        }
    }
    for (;;) {
        if (me->_state == 0) {
            // State: START
            if (!me->_entered) {
                me->_entered = true;
            }
            else {
                if (me->_input.event.INIT) {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
            }
        }
        else {
            // State: GetInputs
            if (!me->_entered) {
                WagoInputBlock_GetKBusInputs(me);
                me->_output.event.CNF = 1;
                me->_entered = true;
            }
            else {
                me->_state = 1;
                me->_entered = false;
                continue;
            }
        }
        break;
    }
    me->_input.events = 0;

    if (me->_output.event.CNF) {
        me->_DI0 = me->DI0;
        me->_DI1 = me->DI1;
        me->_DI2 = me->DI2;
        me->_DI3 = me->DI3;
        me->_DI4 = me->DI4;
        me->_DI5 = me->DI5;
        me->_DI6 = me->DI6;
        me->_DI7 = me->DI7;
    }
}

