// This file is generated by FBC.

#ifndef WAGOINPUTBLOCK_H_
#define WAGOINPUTBLOCK_H_

#include "fbtypes.h"
#include "kbusapi.h"
@addObjDependency#kbusapi.o

typedef union {
    UDINT events;
    struct {
        UDINT INIT : 1; // Initialization Request
    } event;
} WagoInputBlockIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT CNF : 1; // Execution Confirmation
    } event;
} WagoInputBlockOEvents;

// Basic Function Block Type
typedef struct {
    UINT _state;
    BOOL _entered;
    WagoInputBlockIEvents _input;
    INT ByteIndex;
    INT _ByteIndex;
    WagoInputBlockOEvents _output;
    BOOL DI0;
    BOOL _DI0;
    BOOL DI1;
    BOOL _DI1;
    BOOL DI2;
    BOOL _DI2;
    BOOL DI3;
    BOOL _DI3;
    BOOL DI4;
    BOOL _DI4;
    BOOL DI5;
    BOOL _DI5;
    BOOL DI6;
    BOOL _DI6;
    BOOL DI7;
    BOOL _DI7;
} WagoInputBlock;

/* Function block initialization function */
void WagoInputBlockinit(WagoInputBlock* me);

/* Function block execution function */
void WagoInputBlockrun(WagoInputBlock* me);

/* ECC algorithms */
void WagoInputBlock_GetKBusInputs(WagoInputBlock* me);

#endif // WAGOINPUTBLOCK_H_

