// This file is generated by FBC.
#include "AND@unique@.h"
#include <string.h>

/* AND initialization function */
void AND@unique@init(AND@unique@* me)
{
    memset(me, 0, sizeof(AND@unique@));
}

/* AND@unique@ execution function */
void AND@unique@run(AND@unique@* me)
{
	me->_output.events = 0;

	if (me->_input.event.REQ) {
		me->_OUT = true; // done this weird long way because of how templates are made (can't do single line &)
		@begin_varlist#IN@
		me->_OUT &= me->_@var@;
		@end_varlist@
		me->_output.event.CNF = 1;
	}
	
	me->_input.events = 0;
	
}
