// This file is generated by FBC.

#ifndef AND@unique@_H_
#define AND@unique@_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT REQ : 1;
    } event;
} AND@unique@IEvents;

typedef union {
    UDINT events;
    struct {
        UDINT CNF : 1;
    } event;
} AND@unique@OEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    AND@unique@IEvents _input;
    AND@unique@OEvents _output;
	
	@begin_varlist#IN@
	BOOL _@var@;
	@end_varlist@
	
	BOOL _OUT;
	
} AND@unique@;

/* AND@unique@ initialization function */
void AND@unique@init(AND@unique@* me);

/* AND@unique@ execution function */
void AND@unique@run(AND@unique@* me);

#endif	// AND@unique@_H_
