// This file is generated by FBC.

#ifndef E_RESTART_H_
#define E_RESTART_H_

#include "fbtypes.h"


typedef union {
    UDINT events;
    struct {
        UDINT COLD : 1; // cold restart
        UDINT WARM : 1; // warm restart
        UDINT STOP : 1; // event issued prior to stopping the resource
    } event;
} E_RESTARTOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    E_RESTARTOEvents _output;
} E_RESTART;

/* E_RESTART initialization function */
void E_RESTARTinit(E_RESTART* me);

/* E_RESTART execution function */
void E_RESTARTrun(E_RESTART* me);

#endif	// E_RESTART_H_
