// This file is generated by FBC.

#include "E_RESTART.h"

/* E_RESTART initialization function */
void E_RESTARTinit(E_RESTART* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_output.events = 0;
}

/* E_RESTART execution function */
void E_RESTARTrun(E_RESTART* me)
{
    me->_output.events = 0;
    
    if (me->_state == 0) {
        if (!me->_entered) {
            me->_entered = true;
        }
        else {
            me->_output.event.COLD = 1;
            me->_state = 1;
        }
    }
}
