// This file is generated by FBC.

#include "pubsub.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>


/* DESCRIPTION: Initialize the publisher to enable multicasting
 * ARGUMENTS: me - self-referential pointer to publisher object
 *            ttl - time-to-live (set to 0 for local communication)
 *            id - multicast group ID
 */
void openPublisher(Publisher* me, unsigned char ttl, char* id)
{
	// Open a UDP socket
	me->sockfd = socket(PF_INET, SOCK_DGRAM, 0);
	if (me->sockfd < 0) {
		perror("Publ: Error creating socket.");
		exit(EXIT_FAILURE);
	}

	me->myAddr.sin_family = AF_INET;
	me->myAddr.sin_port = htons(0);					// use the first free port
	me->myAddr.sin_addr.s_addr = htonl(INADDR_ANY);	// bind socket to any interface
	
	// Set the outgoing interface to DEFAULT
	struct in_addr iaddr;
	iaddr.s_addr = htonl(INADDR_ANY);	// use DEFAULT interface
	setsockopt(me->sockfd, IPPROTO_IP, IP_MULTICAST_IF, &iaddr, sizeof(iaddr));

	// Set multicast packet TTL
	setsockopt(me->sockfd, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl));
	me->ttl = ttl;

	// Send multicast traffic to myself too
	unsigned char loop = 1;
	setsockopt(me->sockfd, IPPROTO_IP, IP_MULTICAST_LOOP, &loop, sizeof(loop));
	
	if ( bind(me->sockfd, (struct sockaddr *)&(me->myAddr), sizeof(me->myAddr)) < 0 ) {
		perror("Publ: Error binding socket to interface.");
		exit(EXIT_FAILURE);
	}
		
	// Set destination multicast address
	char dstAddr[32];
	char* token;
	assert(strlen(id) < 32);
	strcpy(dstAddr, id);
	me->dstAddr.sin_family = AF_INET;
	token = strtok(dstAddr, ":");
	me->dstAddr.sin_addr.s_addr = inet_addr(token);
	token = dstAddr + strlen(token) + 1;
	me->dstAddr.sin_port = htons( (unsigned short)strtol(token, NULL, 10) );
}

/* DESCRIPTION: Format and send data out in a datagram  
 * ARGUMENTS: me - self-referential pointer to publisher object
 *            sd - data to be publish
 *            count - number of data
 */
void sendPublisher(Publisher* me, ANY* sd, int count)
{
	size_t size = 0;
	int i;
	for (i = 0; i < count; i++) {
		assert((size + sizeof(sd[i].len)) <= UDPBUFSIZE);
		memmove(me->buffer + size, &(sd[i].len), sizeof(sd[i].len));
		size += sizeof(sd[i].len);
		assert((size + sd[i].len) <= UDPBUFSIZE);
		memmove(me->buffer + size, sd[i].buf, sd[i].len);
		size += sd[i].len;
	}
	
	if ( sendto(me->sockfd, me->buffer, size, 0, (struct sockaddr*)&(me->dstAddr), 
	            sizeof(me->dstAddr)) < 0 ) {
		perror("Publ: Error sending data through socket.");
	}
}

/* DESCRIPTION: Close the socket connection
 * ARGUMENTS: me - self-referential pointer to publisher object
 */
void closePublisher(Publisher* me)
{
	shutdown(me->sockfd, 2);	// shutdown socket
	close(me->sockfd);			// close socket
}
