// This file is generated by FBtoStrl.

#ifndef PUBSUB_H_
#define PUBSUB_H_

#include <stdbool.h>
#include <netinet/in.h>

#define UDPBUFSIZE 4096	// maximum size of a UDP packet

#ifndef ANY_BUF_SIZE
#define ANY_BUF_SIZE 32
#endif
typedef struct {
	size_t len;
	char buf[ANY_BUF_SIZE];
} ANY;

typedef struct {
	int sockfd;					// socket file descriptor
	unsigned char ttl;			// time-to-live
	char buffer[UDPBUFSIZE];	// sending buffer
	struct sockaddr_in myAddr;	// my address
	struct sockaddr_in dstAddr;	// destination address
} Publisher;
void openPublisher(Publisher* me, unsigned char ttl, char* id);
void sendPublisher(Publisher* me, ANY* sd, int count);
void closePublisher(Publisher* me);

typedef struct {
	int sockfd;					// socket file descriptor
	char buffer[UDPBUFSIZE];	// receiving buffer
	struct sockaddr_in myAddr;	// my address
	struct in_addr groupIP;		// multicast group IP
} Subscriber;
void openSubscriber(Subscriber* me, char* id);\
void receiveSubscriber(Subscriber* me, ANY* rd, int count, bool* rx);
void closeSubscriber(Subscriber* me);


#endif /*PUBSUB_H_*/
