// This file is generated by FBC.

#include "pubsub.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <errno.h>


/* DESCRIPTION: Initialize the subscriber
 * ARGUMENTS: me - self-referential pointer to subscriber object
 *            id - multicast group ID
 */
void openSubscriber(Subscriber* me, char* id)
{
	// Open a UDP socket
	me->sockfd = socket(PF_INET, SOCK_DGRAM, 0);
	if (me->sockfd < 0) {
		perror("Subl: Error creating socket.");
		exit(EXIT_FAILURE);
	}
	
	// Extract multicast group address
	struct ip_mreq imreq;
	char addr[32];
	char* token;
	assert(strlen(id) < 32);
	strcpy(addr, id);
	token = strtok(addr, ":");
	if ( !inet_aton(token, &(me->groupIP)) ) {
		perror("Subl: Multicast address error.");
		exit(EXIT_FAILURE);
	}
	imreq.imr_multiaddr.s_addr = me->groupIP.s_addr;
	imreq.imr_interface.s_addr = htonl(INADDR_ANY);	// use DEFAULT interface
	token = addr + strlen(token) + 1;
	me->myAddr.sin_family = AF_INET;
	me->myAddr.sin_addr.s_addr = htonl(INADDR_ANY); // bind socket to DEFAULT interface
	me->myAddr.sin_port = htons( (unsigned short)strtol(token, NULL, 10) );

	// Join multicast group on default interface
	setsockopt(me->sockfd, IPPROTO_IP, IP_ADD_MEMBERSHIP, &imreq, sizeof(imreq));
	
	// Allow port number to be reuse
	int reuse = 1;
	setsockopt(me->sockfd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));
	
	if (bind(me->sockfd, (struct sockaddr *)&(me->myAddr), sizeof(me->myAddr)) < 0) {
		perror("Subl: Error binding socket to interface.");
		exit(EXIT_FAILURE);
	}
	
	// Set non-blocking read on socket
	int flags = fcntl (me->sockfd, F_GETFL, 0);
	if (flags == -1) {
		perror("Subl: Error getting file status flags.");
		exit(EXIT_FAILURE);
	}
	else
		flags |= O_NONBLOCK;
		
	flags = fcntl(me->sockfd, F_SETFL, flags);
	if (flags == -1) {
		perror("Subl: Error setting file status flags.");
		exit(EXIT_FAILURE);
	}
}

/* DESCRIPTION: Extract the data from the datagram  
 * ARGUMENTS: me - self-referential pointer to subscriber object
 *            rd - subscribed data
 *            count - number of data
 *            rx - set to TRUE if data was received, FALSE otherwise
 */
void receiveSubscriber(Subscriber* me, ANY* rd, int count, bool* rx)
{
	// Receive packet from socket
	//len = recv(sock, buffer, UDPBUFSIZE, 0);
	struct sockaddr_in publaddr;
	socklen_t socklen = sizeof(publaddr);
	*rx = false;
	int len = recvfrom(me->sockfd, me->buffer, UDPBUFSIZE, 0, 
	                   (struct sockaddr*)&publaddr, &socklen);
	if (len >= 0) {
		//printf("Received from: %s:%d\n", inet_ntoa(publaddr.sin_addr), ntohs(publaddr.sin_port));
		*rx = true;
		int size = 0;
		int i;
		for (i = 0; i < count; i++) {
			memmove(&rd[i].len, me->buffer + size, sizeof(rd[i].len)); 
			size += sizeof(rd[i].len);
			assert(rd[i].len <= ANY_BUF_SIZE);
			memmove(rd[i].buf, me->buffer + size, rd[i].len);
			size += rd[i].len;
			if (size >= len)
				break;
		}
	}
}

/* DESCRIPTION: Close the socket connection
 * ARGUMENTS: me - self-referential pointer to subscriber object
 */
void closeSubscriber(Subscriber* me)
{
	shutdown(me->sockfd, 2);	// shutdown socket
	close(me->sockfd);			// close socket
}
