// This file is generated by FBC.
// Sets up inter-resource receive socket

#ifndef COMMCHANNELUDPRECV_H_
#define COMMCHANNELUDPRECV_H_

#include "fbtypes.h"
@copyFile#../PUBSUB/pubsub.h
@copyFile#../PUBSUB/pubsub.c
#include "pubsub.h"
@copyFile#../nxtControl/NxtCommunication.h
@copyFile#../nxtControl/NxtCommunication.c
#include "NxtCommunication.h"
@copyFile#../nxtControl/NxtHMIData.h
@copyFile#../nxtControl/NxtHMIData.c


typedef union {
    UDINT events;
    struct {
        UDINT INIT : 1; // Ev1
    } event;
} COMMCHANNELUDPRECVIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT INITO : 1; // Event Out
    } event;
} COMMCHANNELUDPRECVOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    COMMCHANNELUDPRECVIEvents _input;
    COMMCHANNELUDPRECVOEvents _output;
	
	BOOL QI;
	BOOL _QI;
	char OWNADDR[32];
	char _OWNADDR[32];
    
	BOOL QO;
	BOOL _QO;
	char STATUS[32];
	char _STATUS[32];
	
	BOOL inited;
	
#ifdef _MSC_VER
	SOCKET channelRecvSock;					// socket file descriptor
#else
	int channelRecvSock;					// socket file descriptor
#endif

	struct sockaddr_in server;
	
	SocketLinkedList clients;
	
} COMMCHANNELUDPRECV;


/* COMMCHANNELUDPRECV initialization function */
void COMMCHANNELUDPRECVinit(COMMCHANNELUDPRECV* me);

/* COMMCHANNELUDPRECV execution function */
void COMMCHANNELUDPRECVrun(COMMCHANNELUDPRECV* me);

int COMMCHANNELUDPRECVopen(COMMCHANNELUDPRECV* me, char* ownAddr);
void COMMCHANNELUDPRECVread(COMMCHANNELUDPRECV* me);
int CommChannelHandlePacket(unsigned char *inbuf, int length, int o);

int CommChannelHandleFBData(unsigned long long chanid, char* source, unsigned char *inbuf, int len, int o);
int CommChannelHandleAdapterData(unsigned long long chanid, char* source, unsigned char *inbuf, int len, int o);
void CommChannelClearEvents();

#endif	// COMMCHANNELUDPRECV_H_
