// This file is generated by FBC.

#ifndef LINKDATARECEIVER@unique@_H_
#define LINKDATARECEIVER@unique@_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT INIT : 1; // Ev1
    } event;
} LINKDATARECEIVER@unique@IEvents;

typedef union {
    UDINT events;
    struct {
        UDINT INITO : 1; // Event Out
    } event;
} LINKDATARECEIVER@unique@OEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    LINKDATARECEIVER@unique@IEvents _input;
    LINKDATARECEIVER@unique@OEvents _output;
	LINKDATARECEIVER@unique@OEvents _preoutput;
	
	BOOL _QI;
	UDINT _CHANID;	
	UDINT _DATAWIREIDS[@CNT@];
	
	BOOL _QO;
	
	@begin_varlist#RD_@
	@type#C@ _@var@;
	@end_varlist@
	
} LINKDATARECEIVER@unique@;

/* LINKDATARECEIVER@unique@ initialization function */
void LINKDATARECEIVER@unique@init(LINKDATARECEIVER@unique@* me);

/* LINKDATARECEIVER@unique@ execution function */
void LINKDATARECEIVER@unique@run(LINKDATARECEIVER@unique@* me);
void LINKDATARECEIVER@unique@_Register(LINKDATARECEIVER@unique@* receiver);

#endif	// LINKDATARECEIVER@unique@_H_
