// This file is generated by FBC

#ifndef SUBL@postfix@_H_
#define SUBL@postfix@_H_

#include "fbtypes.h"
#include "globalvars.h"
@includeUserTypes@

typedef union {
	UDINT events;
	struct {
		UDINT INIT : 1; // service initialization
	} event;
} SUBL@postfix@IEvents;

typedef union {
	UDINT events;
	struct {
		UDINT INITO : 1; // initialization confirm
		UDINT IND : 1; // service indication
	} event;
} SUBL@postfix@OEvents;

typedef struct {
	BOOL _entered;
	SUBL@postfix@IEvents _input;
	@begin_varlist#RD_@
	@type#C@ _@var@;
	@end_varlist@
	SUBL@postfix@OEvents _output;
	@globalType@* _globalBuf;
} SUBL@postfix@;

/* SUBL@postfix@ initialization function */
void SUBL@postfix@init(SUBL@postfix@* me, @globalType@* global);

/* SUBL@postfix@ execution function */
void SUBL@postfix@run(SUBL@postfix@* me);

#endif /*SUBL@postfix@_H_*/
