// This file is generated by FBC.

#ifndef E_TICK_H_
#define E_TICK_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT TICK : 1; // clock tick
    } event;
} E_TICKOEvents;

/* Generation of tick events */
typedef struct {
    E_TICKOEvents _output;
} E_TICK;

/* Function block initialization function */
void E_TICKinit(E_TICK* me);

/* Function block execution function */
void E_TICKrun(E_TICK* me);

#endif // E_TICK_H_

