// This file is generated by FBC.

#include "E_TICK.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void E_TICKinit(E_TICK* me)
{
    me->_output.events = 0;
}

/* Function block execution function */
void E_TICKrun(E_TICK* me)
{
    me->_output.event.TICK = 1;
}
