// This file is generated by FBC.

#ifndef FBTYPES_H_
#define FBTYPES_H_

#if _MSC_VER
#include <winsock2.h>

// Will be defined in some other file
int gettimeofday(struct timeval* tp, void* tzp);
void timersub( const struct timeval * tvp, const struct timeval * uvp, struct timeval * vvp );
#else
#include <sys/time.h>
#endif

#ifndef __cplusplus
#ifndef HAS_BOOLEAN
    typedef char bool;
    #define HAS_BOOLEAN
#endif // HAS_BOOLEAN
#endif // __cplusplus

#ifndef true
    #define true 1
    #define false 0
#endif

#ifndef TRUE
    #define TRUE true
    #define FALSE false
#endif

#define STRING_LENGTH 32

typedef char FBstring[STRING_LENGTH];

#if (__GNUC__ || _MSC_VER)
#define DATE_AND_TIME struct timeval
#endif

#endif // FBTYPES_H_
