// This file is generated by FBC.

#include "PUBLISH_8.h"
#include <string.h>


#include <assert.h>

#ifdef _MSC_VER
#include <Winsock2.h>
#include <Ws2tcpip.h>
#else
#include <stdio.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#endif

/* PUBLISH_8 initialization function */
void PUBLISH_8init(PUBLISH_8* me)
{
    memset(me, 0, sizeof(PUBLISH_8));
}

void PUBLISH_8sendPublisher(PUBLISH_8* me)
{
	Publisher* pub = &me->publish;
	size_t offset = 0, newoffset = 0;
	
	printf("\t\t\tPUBLISH_8sendPublisher\n");
	// TODO: ASN.1 version of:
	//assert((size + sizeof(bool)) <= UDPBUFSIZE);
	// TODO: Error checking? (If newoffset == -1, encoding failed)
	
	newoffset = encodeDERValue(pub->buffer, offset, IEC_BOOL, 1, &(me->_SD_1));
	printHex(pub->buffer, offset, newoffset-offset);
	offset = newoffset;
	
	newoffset = encodeDERValue(pub->buffer, offset, IEC_BOOL, 1, &(me->_SD_2));
	printHex(pub->buffer, offset, newoffset-offset);
	offset = newoffset;
	
	newoffset = encodeDERValue(pub->buffer, offset, IEC_SINT, 1, &(me->_SD_3));
	printHex(pub->buffer, offset, newoffset-offset);
	offset = newoffset;
	
	newoffset = encodeDERValue(pub->buffer, offset, IEC_USINT, 1, &(me->_SD_4));
	printHex(pub->buffer, offset, newoffset-offset);
	offset = newoffset;
	
	newoffset = encodeDERValue(pub->buffer, offset, IEC_USINT, 1, &(me->_SD_5));
	printHex(pub->buffer, offset, newoffset-offset);
	offset = newoffset;
	
	newoffset = encodeDERValue(pub->buffer, offset, IEC_UINT, 1, &(me->_SD_6));
	printHex(pub->buffer, offset, newoffset-offset);
	offset = newoffset;
	
	newoffset = encodeDERValue(pub->buffer, offset, IEC_STRING, 1, &(me->_SD_7));
	printHex(pub->buffer, offset, newoffset-offset);
	offset = newoffset;
	
	newoffset = encodeDERValue(pub->buffer, offset, IEC_DINT, 3, &(me->_SD_8));
	printHex(pub->buffer, offset, newoffset-offset);
	offset = newoffset;
	
	if ( sendto(pub->sockfd, pub->buffer, offset, 0, (struct sockaddr*)&(pub->dstAddr), 
	            sizeof(pub->dstAddr)) < 0 ) {
		perror("Publ: Error sending data through socket.");
#ifdef _MSC_VER
		printf("WSAGetLastError: %d\n", WSAGetLastError());
#endif
	}
}

/* PUBLISH_8 execution function */
void PUBLISH_8run(PUBLISH_8* me)
{
	me->_output.events = 0;

	if (me->_input.event.INIT) {
		printf("pub INIT\n");
		me->QI = me->_QI;
		if( me->QI )
			printf("me->QI\n");
		strncpy(me->ID, me->_ID, MAX_ID_LEN);
	}
	if (me->_input.event.REQ) {
		me->QI = me->_QI;
	}
	
	if (!me->_entered) {
		me->_entered = true;
		printf("pub !_entered\n");
	}
	else {				
		printf("pub _entered\n");	
		if (me->_input.event.INIT) {
			printf("pub QI check\n");
			if (me->QI) {
				printf("openpub\n");
				openPublisher(&me->publish, 1, me->ID);
				me->QO = true;
				strncpy(me->STATUS, "OK", MAX_STATUS_LEN);
				me->_output.event.INITO = 1;
			}
			else {
				closePublisher(&me->publish);
				me->QO = false;
				strncpy(me->STATUS, "", MAX_STATUS_LEN);
				me->_output.event.INITO = 1;
			}
		}
		else if (me->_input.event.REQ) {
			if (me->QI) {
				PUBLISH_8sendPublisher(me);
				me->QO = true;
				strncpy(me->STATUS, "OK", MAX_STATUS_LEN);
				me->_output.event.CNF = 1;
			}
			else {
				me->QO = false;
				strncpy(me->STATUS, "INHIBITED", MAX_STATUS_LEN);
				me->_output.event.CNF = 1;
			}
		}
	}	
	me->_input.events = 0;
	
	if (me->_output.event.INITO || me->_output.event.CNF) {
		me->_QO = me->QO;
		strncpy(me->_STATUS, me->STATUS, MAX_STATUS_LEN);
	}
}
