// This file is generated by FBC.

#include "pubsub.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>


#ifdef _MSC_VER
#include <Winsock2.h>
#include <Ws2tcpip.h>
#else

#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#endif

/* DESCRIPTION: Initialize the publisher to enable multicasting
 * ARGUMENTS: me - self-referential pointer to publisher object
 *            ttl - time-to-live (set to 0 for local communication)
 *            id - multicast group ID
 */
void openPublisher(Publisher* me, unsigned char ttl, char* id)
{
	struct in_addr iaddr;
	unsigned char loop = 1;
	char dstAddr[32];
	char* token;
	
#ifdef _MSC_VER
	unsigned long broadcast = 1;
	WSADATA wsaData;
	WORD version;
	int error;

	version = MAKEWORD( 2, 0 );

	error = WSAStartup( version, &wsaData );
	
	/* check for error */
	if ( error != 0 )
	{
	    printf("WSAStartup Error: %d\n", error);
		exit(EXIT_FAILURE);
	}
#endif

	printf("PUBL on %s\n", id);
	
	
	
	// Open a UDP socket
	me->sockfd = socket(PF_INET, SOCK_DGRAM, 0);
	if (me->sockfd < 0) {
		perror("Publ: Error creating socket.");
		exit(EXIT_FAILURE);
	}

	me->myAddr.sin_family = AF_INET;
	me->myAddr.sin_port = htons(0);					// use the first free port
	me->myAddr.sin_addr.s_addr = htonl(INADDR_ANY);	// bind socket to any interface
	
	// Set the outgoing interface to DEFAULT
	//struct in_addr iaddr;
	iaddr.s_addr = htonl(INADDR_ANY);	// use DEFAULT interface
	if( setsockopt(me->sockfd, IPPROTO_IP, IP_MULTICAST_IF, &iaddr, sizeof(iaddr)) != 0 )
	{
		printf("Publ: Error setsockopt Set the outgoing interface to IP_MULTICAST_IF.");
		exit(EXIT_FAILURE);
	}

	// Set multicast packet TTL
	if( setsockopt(me->sockfd, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl)) != 0 )
	{
		printf("Publ: Error setsockopt Set multicast packet TTL.");
		exit(EXIT_FAILURE);
	}
	me->ttl = ttl;

	// Send multicast traffic to myself too
	if( setsockopt(me->sockfd, IPPROTO_IP, IP_MULTICAST_LOOP, &loop, sizeof(loop)) != 0 )
	{
		printf("Publ: Error setsockopt Send multicast traffic to myself too.");
		exit(EXIT_FAILURE);
	}

#ifdef _MSC_VER
	
	if( setsockopt(me->sockfd, SOL_SOCKET, SO_BROADCAST, (const char*)&broadcast, sizeof(broadcast)) != 0 )
	{
		printf("Publ: Error setsockopt Send multicast traffic to myself too.");
		exit(EXIT_FAILURE);
	}
#endif

	if ( bind(me->sockfd, (struct sockaddr *)&(me->myAddr), sizeof(me->myAddr)) < 0 ) {
		perror("Publ: Error binding socket to interface.");
		exit(EXIT_FAILURE);
	}
		
	// Set destination multicast address
	assert(strlen(id) < 32);
	strcpy(dstAddr, id);
	me->dstAddr.sin_family = AF_INET;
	token = strtok(dstAddr, ":");
	me->dstAddr.sin_addr.s_addr = inet_addr(token);
	token = dstAddr + strlen(token) + 1;
	me->dstAddr.sin_port = htons( (unsigned short)strtol(token, NULL, 10) );
}

/* DESCRIPTION: Close the socket connection
 * ARGUMENTS: me - self-referential pointer to publisher object
 */
void closePublisher(Publisher* me)
{
	shutdown(me->sockfd, 2);	// shutdown socket
#ifdef _MSC_VER
	closesocket(me->sockfd);	// close socket
#else
	close(me->sockfd);			// close socket
#endif
}
