// This file is generated by FBC.

#include "SUBSCRIBE_8.h"
#include <string.h>

#include <assert.h>

#ifdef _MSC_VER
#include <Ws2tcpip.h>
#else
#include <unistd.h>
#include <arpa/inet.h>
#endif
#include  <sys/socket.h>

/* SUBSCRIBE_8 initialization function */
void SUBSCRIBE_8init(SUBSCRIBE_8* me)
{
	memset(me, 0, sizeof(SUBSCRIBE_8));
}

bool SUBSCRIBE_8receiveSubscriber(SUBSCRIBE_8* me)
{
	struct sockaddr_in publaddr;
	socklen_t socklen = sizeof(publaddr);
	Subscriber* sub = &me->subscribe;
	bool rx = false;
	int len;
	int offset = 0, newoffset = 0;
		
	
	while ( (len = recvfrom(sub->sockfd, sub->buffer, UDPBUFSIZE, 0,
			(struct sockaddr*)&publaddr, &socklen)) >= 0 ) {
		printf("\t\t\tReceived from: %s:%d\n", inet_ntoa(publaddr.sin_addr), ntohs(publaddr.sin_port));
		rx = true;
		offset = 0;
		
	// TODO: ASN.1 version of assert?
	// assert((offset + sizeof(@type#C@)) <= UDPBUFSIZE);
	
	newoffset = decodeDERValue(sub->buffer, offset, &(me->_RD_1), sizeof(me->_RD_1));
	printHex(&(me->_RD_1), 0, sizeof(me->_RD_1));
	offset = newoffset;
	
	newoffset = decodeDERValue(sub->buffer, offset, &(me->_RD_2), sizeof(me->_RD_2));
	printHex(&(me->_RD_2), 0, sizeof(me->_RD_2));
	offset = newoffset;
	
	newoffset = decodeDERValue(sub->buffer, offset, &(me->_RD_3), sizeof(me->_RD_3));
	printHex(&(me->_RD_3), 0, sizeof(me->_RD_3));
	offset = newoffset;
	
	newoffset = decodeDERValue(sub->buffer, offset, &(me->_RD_4), sizeof(me->_RD_4));
	printHex(&(me->_RD_4), 0, sizeof(me->_RD_4));
	offset = newoffset;
	
	newoffset = decodeDERValue(sub->buffer, offset, &(me->_RD_5), sizeof(me->_RD_5));
	printHex(&(me->_RD_5), 0, sizeof(me->_RD_5));
	offset = newoffset;
	
	newoffset = decodeDERValue(sub->buffer, offset, &(me->_RD_6), sizeof(me->_RD_6));
	printHex(&(me->_RD_6), 0, sizeof(me->_RD_6));
	offset = newoffset;
	
	newoffset = decodeDERValue(sub->buffer, offset, &(me->_RD_7), sizeof(me->_RD_7));
	printHex(&(me->_RD_7), 0, sizeof(me->_RD_7));
	offset = newoffset;
	
	newoffset = decodeDERValue(sub->buffer, offset, &(me->_RD_8), sizeof(me->_RD_8));
	printHex(&(me->_RD_8), 0, sizeof(me->_RD_8));
	offset = newoffset;



	}

	if( rx )
		printf("SUBSCRIBE_8receiveSubscriber\n");
	
	return rx;
}
	
/* SUBSCRIBE_8 execution function */
void SUBSCRIBE_8run(SUBSCRIBE_8* me)
{
	me->_output.events = 0;

	if (me->_input.event.INIT) {
		me->QI = me->_QI;
		strncpy(me->ID, me->_ID, MAX_ID_LEN);
	}
	if (me->_input.event.RSP) {
		me->QI = me->_QI;
	}
	
	if (!me->_entered) {
		me->_entered = true;
	}
	else {
		if (me->_input.event.INIT) {
			if (me->QI) {
				openSubscriber(&me->subscribe, me->ID);
				me->QO = true;
				strncpy(me->STATUS, "OK", MAX_STATUS_LEN);
				me->_output.event.INITO = 1;
			}
			else {
				closeSubscriber(&me->subscribe);
				me->QO = false;
				strncpy(me->STATUS, "", MAX_STATUS_LEN);
				me->_output.event.INITO = 1;
			}
		}
		else {
			if( SUBSCRIBE_8receiveSubscriber(me) ) {
				me->QO = true;
				strncpy(me->STATUS, "OK", MAX_STATUS_LEN);
				me->_output.event.IND = 1;
			}
		}
	}
	me->_input.events = 0;
	
	if (me->_output.event.INITO) {
		me->_QO = me->QO;
		strncpy(me->_STATUS, me->STATUS, MAX_STATUS_LEN);
	}
	if (me->_output.event.IND) {
		me->_QO = me->QO;
		strncpy(me->_STATUS, me->STATUS, MAX_STATUS_LEN);		
	}
}
