// This file is generated by FBC

#ifndef SUBSCRIBE_8_H_
#define SUBSCRIBE_8_H_

#include "pubsub.h"
#include "ASN1.h"
#include "fbtypes.h"

extern void printHex(unsigned char* buf, int offset, int len);

typedef union {
	unsigned int events;
	struct {
		unsigned int INIT : 1; // service initialization
		unsigned int RSP : 1; // service response
	} event;
} SUBSCRIBE_8IEvents;

typedef union {
	unsigned int events;
	struct {
		unsigned int INITO : 1; // initialization confirm
		unsigned int IND : 1; // service indication
	} event;
} SUBSCRIBE_8OEvents;

#define MAX_ID_LEN 31
#define MAX_STATUS_LEN 31
typedef struct {
	int _state;
	bool _entered;

	SUBSCRIBE_8IEvents _input;
	bool QI;
	bool _QI;
	char ID[MAX_ID_LEN + 1];
	char _ID[MAX_ID_LEN + 1];
	SUBSCRIBE_8OEvents _output;
	bool QO;
	bool _QO;
	char STATUS[MAX_STATUS_LEN + 1];
	char _STATUS[MAX_STATUS_LEN + 1];
	
	bool _RD_1;
	bool _RD_2;
	char _RD_3;
	unsigned char _RD_4;
	unsigned char _RD_5;
	unsigned short _RD_6;
	FBstring _RD_7;
	int _RD_8[3];
	
	Subscriber subscribe;
} SUBSCRIBE_8;

/* SUBSCRIBE_8 initialization function */
void SUBSCRIBE_8init(SUBSCRIBE_8* me);

/* SUBSCRIBE_8 execution function */
void SUBSCRIBE_8run(SUBSCRIBE_8* me);

#endif /*SUBSCRIBE_8_H_*/
