// This file is generated by FBC.

#include "E_DELAY.h"
#include <stddef.h>

void EDelayinit(EDelay* me, int DT)
{
    gettimeofday(&me->startTime, NULL);
    me->DT = DT;
}

int EDelaycheck(EDelay me)
{
    struct timeval curTime, result;
    gettimeofday(&curTime, NULL);
    timersub(&curTime, &me->startTime, &result);
    long long elapsed = (long long)(result.tv_sec) * 1000000 + result.tv_usec;
    return (int)(elapsed/1000);
}
