// This file is generated by FBC.

#ifndef NOT@unique@_H_
#define NOT@unique@_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT REQ : 1;
    } event;
} NOT@unique@IEvents;

typedef union {
    UDINT events;
    struct {
        UDINT CNF : 1;
    } event;
} NOT@unique@OEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    NOT@unique@IEvents _input;
    NOT@unique@OEvents _output;
	
	@begin_varlist#IN@
	BOOL _@var@;
	@end_varlist@
	
	@begin_varlist#OUT@
	BOOL _@var@;
	@end_varlist@
	
} NOT@unique@;

/* NOT@unique@ initialization function */
void NOT@unique@init(NOT@unique@* me);

/* NOT@unique@ execution function */
void NOT@unique@run(NOT@unique@* me);

#endif	// NOT@unique@_H_
