// This file is generated by FBC.
#include "NOT@unique@.h"
#include <string.h>

/* NOT initialization function */
void NOT@unique@init(NOT@unique@* me)
{
    memset(me, 0, sizeof(NOT@unique@));
}

/* NOT@unique@ execution function */
void NOT@unique@run(NOT@unique@* me)
{
	me->_output.events = 0;

	if (me->_input.event.REQ) {
		@begin_varlist#IN@
			me->_OUT@v#@ = !me->_@var@;
		@end_varlist@
		me->_output.event.CNF = 1;
	}
	
	me->_input.events = 0;
	
}
