// This file is generated by FBC

#ifndef VISINTERFACE_H_
#define VISINTERFACE_H_

@copyFile#../PUBSUB/pubsub.h
@copyFile#../PUBSUB/pubsub.c
@copyFile#../PUBSUB/publisher.c
#include "pubsub.h"
#include "fbtypes.h"

typedef union {
	UDINT events;
	struct {
		UDINT INIT : 1; // service initialization
		UDINT REQ : 1; // service request
	} event;
} VisInterfaceIEvents;

typedef union {
	UDINT events;
	struct {
		UDINT INITO : 1; // initialization confirm
		UDINT CNF : 1; // service confirmation
	} event;
} VisInterfaceOEvents;

#define MAX_ID_LEN 31
#define MAX_STATUS_LEN 31
typedef struct {
	UINT _state;
	BOOL _entered;

	VisInterfaceIEvents _input;
	BOOL _QI;
	char _PubTo[MAX_ID_LEN + 1];
	
	INT _BagCount;
	INT _BagIDData[20];
	DINT _BagXPosData[20];
	DINT _BagYPosData[20];
	INT _BagAngleData[20];
	INT _BagLengthData[20];
	INT _BagWidthData[20];
	BOOL _PEDetects[6];
	INT _PEStatus[6];
	INT _ConvStatus;
	INT _ConvExtraStatus;
	
	VisInterfaceOEvents _output;
	BOOL _QO;
	char _STATUS[MAX_STATUS_LEN + 1];

	Publisher publish;
} VisInterface;

/* VisInterface initialization function */
void VisInterfaceinit(VisInterface* me);

/* VisInterface execution function */
void VisInterfacerun(VisInterface* me);
void VisInterfacesendPublisher(VisInterface* me);

#endif /*VISINTERFACE_H_*/
