// This file is generated by FBC.

#ifndef E_CTU_H_
#define E_CTU_H_

#include "fbtypes.h" // for bool

typedef union {
    UDINT events;
    struct {
        UDINT CU : 1; // Count UP
        UDINT R : 1; // Reset
    } event;
} E_CTUIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT CUO : 1; // Count up Out
		UDINT RO : 1; // Reset Out
    } event;
} E_CTUOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    E_CTUIEvents _input;
    E_CTUOEvents _output;

    UINT PV;
	UINT _PV;
    
	UINT _CV;
	BOOL _Q;
	
} E_CTU;

/* E_CTU initialization function */
void E_CTUinit(E_CTU* me);

/* E_CTU execution function */
void E_CTUrun(E_CTU* me);

#endif	// E_CTU_H_
