// This file is generated by FBC.

#ifndef LINKPUBLISHER@unique@_H_
#define LINKPUBLISHER@unique@_H_

#include "fbtypes.h"
#include "COMMCHANNEL.h"

typedef union {
    unsigned int events;
    struct {
        unsigned int INIT : 1; // INIT
		unsigned int REQ : 1; // REQ
    } event;
} LINKPUBLISHER@unique@IEvents;

typedef union {
    unsigned int events;
    struct {
        unsigned int INITO : 1; // INITO
    } event;
} LINKPUBLISHER@unique@OEvents;

typedef struct {
    int _state;
    bool _entered;

    LINKPUBLISHER@unique@IEvents _input;
    LINKPUBLISHER@unique@OEvents _output;
	
	// Inputs
	bool _QI;
	unsigned long long _CHANID;
	unsigned long long _EVENTWIREID;
	unsigned long long _DATAWIREIDS[@CNT@];
	
	char buffer[1024]; // buffer for data send this tiok
	int bufLen; // amount of buffer used
	
	//unsigned short command; // 0x82 = FB, 0x87 = Adapter
	
	COMMCHANNEL* channelHost;

	@begin_varlist#SD_@
	@type#C@ _@var@;
	@end_varlist@
	// Outputs
	bool _QO;
	
} LINKPUBLISHER@unique@;

/* LINKPUBLISHER initialization function */
void LINKPUBLISHER@unique@init(LINKPUBLISHER@unique@* me);

void LINKPUBLISHER@unique@_ConnectChannel(LINKPUBLISHER@unique@* me);

/* LINKPUBLISHER execution function */
void LINKPUBLISHER@unique@run(LINKPUBLISHER@unique@* me);
int LINKPUBLISHER@unique@packdata(LINKPUBLISHER@unique@* me);


#endif	// LINKPUBLISHER_H_
