// This file is generated by FBC.

#ifndef KEYBOARDCAPTURE_H_
#define KEYBOARDCAPTURE_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT keyboardEvent : 1;
    } event;
} keyboardCaptureOEvents;

typedef struct {
    keyboardCaptureOEvents _output;
	char _key;
} keyboardCapture;

/* keyboardCapture initialization function */
void keyboardCaptureinit(keyboardCapture* me);

/* keyboardCapture execution function */
void keyboardCapturerun(keyboardCapture* me);

#endif	// KEYBOARDCAPTURE_H_
