// This file is generated by FBC.

#include "E_DELAY.h"
#include <string.h>

/* E_DELAY initialization function */
void E_DELAYinit(E_DELAY* me)
{
    memset(me, 0, sizeof(E_DELAY));
}

/* E_DELAY execution function */
void E_DELAYrun(E_DELAY* me)
{
	struct timeval curTime, result;
    TIME elapsed;
	
    me->_output.events = 0;

    if (me->_input.event.START) {
        me->DT = me->_DT;
    }
	
    for (;;) {
        switch (me->_state) {
            case 0:
                if (!me->_entered) {
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.START) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 1:
                if (!me->_entered) {
					gettimeofday(&me->startTime, NULL);
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.STOP) {
                        me->_state = 0;
                        me->_entered = false;
                    	continue;
                    }
                    else {
                        gettimeofday(&curTime, NULL);
                        timersub(&curTime, &me->startTime, &result);
                        elapsed = (long long)(result.tv_sec) * 1000000 + result.tv_usec;
                        if (elapsed >= me->DT) {
                            me->_state = 2;
                            me->_entered = false;
                            continue;
                        }
                    }
                }
                break;
            case 2:
                if (!me->_entered) {
                    me->_output.event.EO = 1;
                    me->_entered = true;
                }
                else {
					if (me->_input.event.START) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
					else
					{
						me->_state = 0;
						me->_entered = false;
						continue;
					}
                }
                break;
        }
        break;
    }
    me->_input.events = 0;
}
