// This file is generated by FBC.

#ifndef E_DELAY_H_
#define E_DELAY_H_

#ifdef _MSC_VER
#include <Winsock2.h> // for timeval struct :(
#else
#include <sys/time.h>
#endif
#include "fbtypes.h" // for bool

typedef union {
    UDINT events;
    struct {
        UDINT START : 1; // Begin delay
        UDINT STOP : 1; // Cancel delay
    } event;
} E_DELAYIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT EO : 1; // Delayed event
    } event;
} E_DELAYOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    E_DELAYIEvents _input;
    E_DELAYOEvents _output;

    TIME DT;
    TIME _DT;
    struct timeval startTime;
} E_DELAY;

/* E_DELAY initialization function */
void E_DELAYinit(E_DELAY* me);

/* E_DELAY execution function */
void E_DELAYrun(E_DELAY* me);

#endif	// E_DELAY_H_
