// This file is generated by FBC.

#include "WagoOutputBlock.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void WagoOutputBlockinit(WagoOutputBlock* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.events = 0;
    me->_output.events = 0;
}

/* ECC algorithms */
// Normally executed algorithm
void WagoOutputBlock_SetKBusInputs(WagoOutputBlock* me)
{
// read byte from pab and show it on console
KbusOpen();

pstPabOUT->uc.Pab[me->ByteIndex] = 0x00; // CLEAR

pstPabOUT->uc.Pab[me->ByteIndex] |= me->DO0;// << 0;
pstPabOUT->uc.Pab[me->ByteIndex] |= me->DO1 << 1;
pstPabOUT->uc.Pab[me->ByteIndex] |= me->DO2 << 2;
pstPabOUT->uc.Pab[me->ByteIndex] |= me->DO3 << 3;
pstPabOUT->uc.Pab[me->ByteIndex] |= me->DO4 << 4;
pstPabOUT->uc.Pab[me->ByteIndex] |= me->DO5 << 5;
pstPabOUT->uc.Pab[me->ByteIndex] |= me->DO6 << 6;
pstPabOUT->uc.Pab[me->ByteIndex] |= me->DO7 << 7;

// Write Output values
KbusUpdate();

// Close
KbusClose();

}

/* Function block execution function */
void WagoOutputBlockrun(WagoOutputBlock* me)
{
    me->_output.events = 0;

    if (me->_input.events) {
        if (me->_input.event.INIT) {
            me->ByteIndex = me->_ByteIndex;
        }
        if (me->_input.event.REQ) {
            me->DO0 = me->_DO0;
            me->DO1 = me->_DO1;
            me->DO2 = me->_DO2;
            me->DO3 = me->_DO3;
            me->DO4 = me->_DO4;
            me->DO5 = me->_DO5;
            me->DO6 = me->_DO6;
            me->DO7 = me->_DO7;
        }
    }
    for (;;) {
        if (me->_state == 0) {
            // State: START
            if (!me->_entered) {
                me->_entered = true;
            }
            else {
                if (me->_input.event.INIT) {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
            }
        }
        else {
            // State: SetOutputs
            if (!me->_entered) {
                WagoOutputBlock_SetKBusInputs(me);
                me->_output.event.CNF = 1;
                me->_entered = true;
            }
            else {
                if (me->_input.event.REQ) {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
            }
        }
        break;
    }
    me->_input.events = 0;

}

