// This file is generated by FBC.

#include "SENDuCOS@postfix@.h"
#include "includes.h"

/* Function block initialization function */
void SENDuCOS@postfix@init(SENDuCOS@postfix@* me, void (*sMsg)(void* msg, UINT sample), void (*sNull)(UINT sample))
{
    me->_entered = false;
    me->_input.events = 0;
    me->_output.events = 0;
	me->hasMsg = false;
    me->_sendMsg = sMsg;
    me->_sendNull = sNull;
	me->_sample = 0;
}

/* Function block execution function */
void SENDuCOS@postfix@run(SENDuCOS@postfix@* me)
{
    me->_output.events = 0;

    if (!me->_entered) {
        me->_entered = true;
    }
    else {
#if (@replaceVarString#sendPeriod@ > @replaceVarString#recvPeriod@)
        if (me->_input.event.REQ) {
            me->hasMsg = true;
            me->_output.event.CNF = 1;
        }
        else
            me->hasMsg = false;
#else
        if (me->_input.event.REQ) {
            OSSchedLock();
            ( *(me->_sendMsg) )(&me->_SD_1, me->_sample);
            OSSchedUnlock();
            me->_output.event.CNF = 1;
        }
        else {
            OSSchedLock();
            ( *(me->_sendNull) )(me->_sample);
            OSSchedUnlock();
        }
        me->_sample++;
        if (me->_sample >= @replaceVarString#TrOverGCD@)	// @replaceVarString#recvPeriod@/@replaceVarString#gcd@
            me->_sample = 0;
#endif
    }

    me->_input.events = 0;
}

#if (@replaceVarString#sendPeriod@ > @replaceVarString#recvPeriod@)
/* Delayed send function */
void SENDuCOS@postfix@send(SENDuCOS@postfix@* me)
{
    OSSchedLock();
    if (me->hasMsg)
        ( *(me->_sendMsg) )(&me->_SD_1, me->_sample);
    else    
        ( *(me->_sendNull) )(me->_sample);	
    OSSchedUnlock();
}
#endif
