// This file is generated by FBC.

#ifndef E_CYCLE_H_
#define E_CYCLE_H_

#ifdef _MSC_VER
#include <Winsock2.h> // for timeval 
#else
#include <sys/time.h>
#endif
#include "fbtypes.h" // for bool

typedef union {
    UDINT events;
    struct {
        UDINT START : 1; // Begin delay
        UDINT STOP : 1; // Cancel delay
    } event;
} E_CYCLEIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT EO : 1; // Delayed event
    } event;
} E_CYCLEOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    E_CYCLEIEvents _input;
    E_CYCLEOEvents _output;

    TIME DT;
    TIME _DT;
    struct timeval startTime;
} E_CYCLE;

/* E_CYCLE initialization function */
void E_CYCLEinit(E_CYCLE* me);

/* E_CYCLE execution function */
void E_CYCLErun(E_CYCLE* me);

#endif	// E_CYCLE_H_
