// This file is generated by FBC.
#include "OR@unique@.h"
#include <string.h>

/* OR initialization function */
void OR@unique@init(OR@unique@* me)
{
    memset(me, 0, sizeof(OR@unique@));
}

/* OR@unique@ execution function */
void OR@unique@run(OR@unique@* me)
{
	me->_output.events = 0;

	if (me->_input.event.REQ) {
		me->_OUT = false;
		@begin_varlist#IN@
		me->_OUT |= me->_@var@;
		@end_varlist@
		me->_output.event.CNF = 1;
	}
	
	me->_input.events = 0;
	
}
