// This file is generated by FBC.

#ifndef OR@unique@_H_
#define OR@unique@_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT REQ : 1;
    } event;
} OR@unique@IEvents;

typedef union {
    UDINT events;
    struct {
        UDINT CNF : 1;
    } event;
} OR@unique@OEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    OR@unique@IEvents _input;
    OR@unique@OEvents _output;
	
	@begin_varlist#IN@
	BOOL _@var@;
	@end_varlist@
	
	BOOL _OUT;
	
} OR@unique@;

/* OR@unique@ initialization function */
void OR@unique@init(OR@unique@* me);

/* OR@unique@ execution function */
void OR@unique@run(OR@unique@* me);

#endif	// OR@unique@_H_
