// This file is generated by FBC.

#ifndef LINKEVENTRECEIVER@unique@_H_
#define LINKEVENTRECEIVER@unique@_H_

#include "fbtypes.h"
#include "COMMCHANNELUDPRECV.h"

typedef union {
    UDINT events;
    struct {
        UDINT INIT : 1; // Ev1
    } event;
} LINKEVENTRECEIVER@unique@IEvents;

typedef union {
    UDINT events;
    struct {
        UDINT INITO : 1; // Event Out
		UDINT IND_@indexRange#1@ : 1;
    } event;
} LINKEVENTRECEIVER@unique@OEvents;

typedef struct {
    UINT _state;
    BOOL _entered;

    LINKEVENTRECEIVER@unique@IEvents _input;
    LINKEVENTRECEIVER@unique@OEvents _output;
	LINKEVENTRECEIVER@unique@OEvents _preoutput;
	
	BOOL _QI;
	UDINT _CHANID;	
	UDINT _EVENTWIREIDS[@index@];
	
	BOOL _QO;
	
} LINKEVENTRECEIVER@unique@;

/* LINKEVENTRECEIVER@unique@ initialization function */
void LINKEVENTRECEIVER@unique@init(LINKEVENTRECEIVER@unique@* me);

/* LINKEVENTRECEIVER@unique@ execution function */
void LINKEVENTRECEIVER@unique@run(LINKEVENTRECEIVER@unique@* me);
void LINKEVENTRECEIVER@unique@_Register(LINKEVENTRECEIVER@unique@* receiver);

#endif	// LINKEVENTRECEIVER@unique@_H_
