// This file is generated by FBC.

#include "E_MERGE.h"
#include <string.h>

/* E_MERGE initialization function */
void E_MERGEinit(E_MERGE* me)
{
    memset(me, 0, sizeof(E_MERGE));
}

/* E_MERGE execution function */
void E_MERGErun(E_MERGE* me)
{
    me->_output.events = 0;

    if( me->_input.events )
	{
        me->_output.event.EO = 1;
    }
	
    me->_input.events = 0;
}
