// This file is generated by FBC.

#include "pubsub.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <fcntl.h>


#ifdef _MSC_VER
#include <Winsock2.h>
#include <Ws2tcpip.h>
#else

#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#endif

#include <errno.h>


/* DESCRIPTION: Initialize the subscriber
 * ARGUMENTS: me - self-referential pointer to subscriber object
 *            id - multicast group ID
 */
void openSubscriber(Subscriber* me, char* id)
{
	struct ip_mreq imreq;
	char addr[32];
	char* token;
	int reuse = 1;
	int flags;

#ifdef _MSC_VER
	WSADATA wsaData;
	WORD version;
	int error;

	version = MAKEWORD( 2, 0 );

	error = WSAStartup( version, &wsaData );
	
	/* check for error */
	if ( error != 0 )
	{
	    printf("SUBSCRIBER - WSAStartup Error: %d\n", error);
		exit(EXIT_FAILURE);
	}
#endif

	printf("SUBSCRIBER - Connecting to %s\n", id);

	// Open a UDP socket
	me->sockfd = socket(PF_INET, SOCK_DGRAM, 0);
	if (me->sockfd < 0) {
		perror("SUBSCRIBER - Error creating socket");
		exit(EXIT_FAILURE);
	}

	// Extract multicast group address
	assert(strlen(id) < 32);
	strcpy(addr, id);
	token = strtok(addr, ":");

	//#Vista +
	/*if ( !inet_pton(AF_INET, token, &(me->groupIP)) ) {
		perror("Subl: Multicast address error.");
		exit(EXIT_FAILURE);
	}
	imreq.imr_multiaddr.s_addr = me->groupIP.s_addr;
	*/
	// #WINXP
	imreq.imr_multiaddr.s_addr = inet_addr(token);
	//


	imreq.imr_interface.s_addr = htonl(INADDR_ANY);	// use DEFAULT interface
	token = addr + strlen(token) + 1;
	me->myAddr.sin_family = AF_INET;
	me->myAddr.sin_addr.s_addr = htonl(INADDR_ANY); // bind socket to DEFAULT interface
	me->myAddr.sin_port = htons( (unsigned short)strtol(token, NULL, 10) );

	// Join multicast group on default interface
	setsockopt(me->sockfd, IPPROTO_IP, IP_ADD_MEMBERSHIP, &imreq, sizeof(imreq));

	// Allow port number to be reuse
	setsockopt(me->sockfd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));

	if (bind(me->sockfd, (struct sockaddr *)&(me->myAddr), sizeof(me->myAddr)) < 0) {
		printf("SUBSCRIBER - Error binding socket to interface");
		exit(EXIT_FAILURE);
	}

	// Set non-blocking read on socket
	#ifndef _MSC_VER
		if (-1 == (flags = fcntl(me->sockfd, F_GETFL, 0)))
			flags = 0;
		flags = fcntl(me->sockfd, F_SETFL, flags | O_NONBLOCK);
		if (flags != 0) {
			perror("SUBSCRIBER - Error setting socket to non-blocking");
			exit(EXIT_FAILURE);
		}
	#else
		flags = 1;
		flags = ioctlsocket(me->sockfd, FIONBIO, &flags);
		if (flags == -1) {
			perror("SUBSCRIBER - Error setting file status flags");
			exit(EXIT_FAILURE);
		}
	#endif
}

/* DESCRIPTION: Close the socket connection
 * ARGUMENTS: me - self-referential pointer to subscriber object
 */
void closeSubscriber(Subscriber* me)
{
	shutdown(me->sockfd, 2);	// shutdown socket
#ifdef _MSC_VER
	closesocket(me->sockfd);	// close socket
#else
	close(me->sockfd);			// close socket
#endif
}
